"""changedtofloatvalues

Revision ID: e0386c2842e6
Revises: 1ed6ecf2f579
Create Date: 2023-02-07 15:08:33.369993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0386c2842e6'
down_revision = '1ed6ecf2f579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Accounts', schema=None) as batch_op:
        batch_op.alter_column('Balance',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.alter_column('Amount',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('NewBalance',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.alter_column('NewBalance',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('Amount',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('Accounts', schema=None) as batch_op:
        batch_op.alter_column('Balance',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
